all: create-container print-container

create-container: create-container.c
	$(CC) -g -Wall -Wextra -I. $^ -o $@ -lssl -lcrypto -std=gnu99

print-container: print-container.c
	$(CC) -g -Wall -Wextra -I. $^ -o $@ -lssl -lcrypto -std=gnu99

clean:
	$(RM) create-container print-container

